# Generated by Django 2.2.5 on 2019-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('percent_has_petro', models.FloatField()),
                ('percent_has_elec', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_email', models.CharField(max_length=50)),
                ('energy_type', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('seller_email', 'energy_type')},
            },
        ),
    ]
