# Generated by Django 2.2.6 on 2019-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
        migrations.RemoveField(
            model_name='country',
            name='percent_has_elec',
        ),
        migrations.RemoveField(
            model_name='country',
            name='percent_has_petro',
        ),
        migrations.AddField(
            model_name='country',
            name='percent_pop_needs_elec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seller',
            name='price_per_kwh',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='seller',
            name='total_produced_2018_Gwh',
            field=models.FloatField(default=0.0),
        ),
    ]
